exp_project: "angle_reconstruction_combine_reco_mc_v4"
exp_name: "encoder_nl5_hs512_dff512_nh1_lr1e3_bs256_nm250_wr0_wm10_da_k0_gr0_mc2020_no-angle-head"
dataset_weights: [0., 1.0]

# from_checkpoint: "/home/plotnikovgp/Baikal-ML/pytorch_training/checkpoints/angle_reconstruction_combine_reco_mc_v4/encoder_nl5_hs512_dff512_nh1_lr1e4_bs256_nm250_wr0_wm10_da_k02_gr0_dp0_mc2020/best_reco.ckpt"
# val_mode: True

lr: 1.0e-4
batch_size: &batch_size 256
tres_cut: 100000.0
num_train_steps_per_validation: 500
accumulate_grad_steps: 1
train_type: "angle_reconstruction_domain_adaptation" 
is_graph: False
grad_clip_value: 1.0
warmup_steps: 500
events_amount: 10000000
use_mae_loss: True

nll_loss_k: 0.0
angle_loss_k: 1.0

domain_adaptation_loss_k: 0.0
gradient_reversal_alpha: &gradient_reversal_alpha 0.0

label_dataset_name: "mc2020"
save_best_per_dataset: True 

dataset_configs:
  -
    path_to_data: &p1 "/home/plotnikovgp/Baikal-ML/pytorch_training/data/baikal_reco_reco_h8s2_norm.h5"
    name: "reco"
    tres_cut: 10000.0
    val_subset_cut: 5
    data_prefilter_params:
      data_file: *p1
      norm_Q: True
  -
    path_to_data: &p2 "/home/plotnikovgp/Baikal-ML/pytorch_training/data/baikal_mc2020_multi_split_MChits-8-2_track-caskade-nue2_normed_.h5"
    name: "mc2020"
    tres_cut: 10000.0
    val_subset_cut: 60
  # -
  #   path_to_data: /home/plotnikovgp/Baikal-ML/pytorch_training/data/baikal_exp-data-single-0324_flat_norm.h5
  #   name: "exp_data"
  #   val_subset_cut: 30
  #   DatasetType: 'no_labels'
  #   preprocessor: 'no_labels'

# from_checkpoint: "/home/plotnikovgp/Baikal-ML/pytorch_training/checkpoints/angle_reconstruction_combine_reco_mc/encoder_nl5_hs512_dff512_nh1_lr1e4_bs256_nm250_wr5_wm5_da_k01_gr001_dp0_mae-loss_use-mean-not-cls/best_mc2020.ckpt"

model_type: "encoder_domain_adaptation"
model_params:
  in_features: 5
  hidden_size: &hidden_size 512
  num_layers: &num_layers 5
  dim_feedforward_size: &dff 512
  n_heads: &n_heads 1
  out_size: 3
  dropout_p: 0.0
  use_batch_norm: False
  num_domains: 2  # Two datasets: reco and mc2020
  domain_classifier_hidden_size: 128
  domain_classifier_layers: 2
  gradient_reversal_alpha: *gradient_reversal_alpha
  use_cls_token: True
  return_only_cls_token: True
