---
train_type: "direction"
# path_to_data: "/home/plotnikovgp/baikal/data/baikal_multi_0324_flat_treck-cascade_h8_s2_pureMC_normed-2strings.h5"
label_dataset_name: "mc2020" 

save_best_per_dataset: True 

path_to_data: "/home/plotnikovgp/Baikal-ML/pytorch_training/data/baikal_mc2020_multi_split_0924h8s2_tl100_norm_wcluster_fix.h5"
from_checkpoint: "/home/plotnikovgp/Baikal-ML/pytorch_training/checkpoints/angle_reconstruction_combine_reco_mc/encoder_nl5_hs512_dff512_nh1_lr1e4_bs128_nm250_wr5_wm5/best_reco.ckpt"
is_graph: False
model_type: "encoder"
model_params:
  in_features: 5
  hidden_size: 512
  num_layers: 3
  dim_feedforward_size: 512
  n_heads: 2
  out_size: 3
  dropout_p: 0.0
  second_head_out_size: 3

lr: 1.0e-4
batch_size: 128
accumulate_grad_steps: 1
num_train_steps_per_validation: 25
grad_clip_value: 1.0
warmup_steps: 1000
distance_loss_coef: 0.
exp_name: "encoder_nl5_hs512_dff512_nh2_lr1e4_track-len100_only-dist-loss"
exp_project: "direction_v1_mc_0924"
val_subset_cut: 3
